### ISSUE TITLE
incidence() supports ISOweek for weekly incidence

### ISSUE THREAD

**Issue by caijun** [reconhub/incidence#12]
When setting interval = 1 in `incidence()`, I can get a perfect daily incidence; however, setting interval = 7 can produce a weekly incidence,  dates of which are not corresponding to [ISO week](https://en.wikipedia.org/wiki/ISO_week_date). You know, most weekly case reports in disease surveillance are based on ISO week. There is an R package called [ISOweek](https://cran.r-project.org/web/packages/ISOweek/index.html), which can convert date from standard notation to week notation according to ISO 8601. It would be much convenient that `incidence()` can support ISOweek-based weekly incidence. Here is my idea to implement this feature for `incidence()`.

1.When interval = 7,  convert input `dates` of `incidence()` function to ISOweeks

2. Modify `count.dates` function to support ISOweek or add a similar function `count.ISOweeks`

I think this feature can be easily implemented, but useful.

**Comment by thibautjombart** [comment]
I agree! It will be part of the next release.
Will try to work on it soon but feel free to PR if you fancy.

Best

Thibaut

**Comment by caijun** [comment]
I will try to PR for this feature for `incidence()` function.

**Comment by thibautjombart** [comment]
Great! I have just created a branch isoweek for you to pull against. Remember to add yourself as contributor to the DESCRIPTION file. As for the implementation, I would add an argument `iso_week` to `incidence`, which defaults to `TRUE` to handle this behaviour.

**Comment by thibautjombart** [comment]
I merged your PR into isoweek, thanks. There are some things to fix before putting it into the master.
https://github.com/reconhub/incidence/blob/isoweek/R/incidence.R#L143:L145
is wrong I think. For instance it leeds to:
```
> incidence(20, interval=7)$dates
Dates stored as decimal numbers were floored.

[1]  0  7 14
```

Moreover, the treatment as ISOweek is currently mandatory as soon as `interval==7`. I would like to see an argument to `incidence.Date` and `incidence.POSIXt` called `isoweek` that would default to `TRUE`. If `FALSE`, previous implementation should be kept. 

Makes sense?

**Comment by caijun** [comment]
Thanks for pointing out the incorrect implementation https://github.com/reconhub/incidence/blob/isoweek/R/incidence.R#L143:L145
and fixing the travis checks.

Adding an argument to `incidence.Date` and `incidence.POSIXT` to keep the previous implementation is a good idea, I will implement it quickly.

**Comment by thibautjombart** [comment]
Awesome. Much appreciated! :) 
Also, you're officially contributing to a RECON package.. wanna join the gang? ;) 
http://www.repidemicsconsortium.org/join/

**Comment by caijun** [comment]
Yes, with pleasure. Though I am the creator of two R packages, by now I haven't created any R packages related to epidemics. I am a PhD candidates focusing on influenza transmission dynamics and creating an R epidemic package is always one of my goals. Actually I talked to you during this summer's R user conference. Your presentation was very impressive.

**Comment by thibautjombart** [comment]
Haha, sorry about this, I should have remembered :) Nice to work together on this!

**Comment by caijun** [comment]
I have added the argument `iso_week` to `incidence.Date` and `incidence.POSIXT`, and updated documents. Could you help review the code?

**Comment by thibautjombart** [comment]
Great, previous plots restored and now tests passing again. Gave it a few tries, seems to work like a charm :)

One remaining thing I'm not sure about. Regarding the labels. Because as.data.frame returns the isoweeks I think it should be possible to plot dates as isoweeks too. But I'm not sure if ggplot2 handles them? If so maybe yet another argument like iso_week_labels = iso_week by default?
