### ISSUE TITLE
strange problem in plotting

### ISSUE THREAD

**Issue by robertogattabs** [reconhub/incidence#121]
Probably it's my fault, but with the following lines:

dat <- ebola_sim$linelist$date_of_onset
i.7 <- incidence(dat, interval = 7)
plot(i.7)

I get the following plot:

![image](https://user-images.githubusercontent.com/11758254/76760474-04b1ce80-678e-11ea-96a8-03a7e9e222b2.png)

**Comment by thibautjombart** [comment]
Hi there, 
it is a bug, which has been reported before. This [PR](https://github.com/reconhub/incidence/pull/120) should close it eventually, but in the meantime you can try this patch:

`remotes::install_github("reconhub/incidence@issue_119")`

For further comments / discussions, let's move to the original issue:
https://github.com/reconhub/incidence/issues/119

**Comment by robertogattabs** [comment]
Thx!
