### ISSUE TITLE
Fix issues due to new release of outbreaks

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/incidence#22]
@finlaycampbell the changes in column names in *outbreaks* is breaking all packages that used this; I think *epicontacts* is fixed, but just uncovered a can of worms with *incidence*. Be careful next time you make such changes. This one is useful as it is consistent with snake_case, but I need a heads up for coordinating changes like that.

**Comment by finlaycampbell** [comment]
Sorry about that, these were pushes that we'd talked about/made a few months ago, but they've only just hit CRAN with the new version. Will give you a heads up next time!

**Comment by thibautjombart** [comment]
closed via 339444a78fc27a597468266e95521736fa19d3db
