### ISSUE TITLE
Upcoming scales changes break some test cases

### ISSUE THREAD

**Issue by karawoo** [reconhub/incidence#25]
We're preparing the next release of the `scales` package, and some of the changes appear to cause failing test cases in `incidence`. A summary of the changes to scales is [here](https://github.com/hadley/scales/blob/master/NEWS.md#scales-0419001).

On my machine the tests for `"fit_optim_split"` fail, and this line in `test-plot.R` also throws an error:

```r
p.isoweek <- plot(i.isoweek)
```

Just wanted to give a heads up about these changes to `scales` so you can look into how they are affecting `incidence`.

**Comment by karawoo** [comment]
Quick update: we're planning to submit the next scales release on August 21.

**Comment by thibautjombart** [comment]
Hi @karawoo and thanks for the heads up! 
@caijun would you like to look into this? It seems to have something to do with `isoweeks`.

**Comment by caijun** [comment]
I will take a look at it and try to fix it.

**Comment by caijun** [comment]
After deleting all rds files under rds directory, all tests passed on my macOS. 

```
==> devtools::test()

Loading incidence
Loading required package: testthat
Testing incidence
Conversions of incidence objects: .......
Test fit functions: .........
Incidence main function: ...........................................................
Non-exported functions: ...............
Color palettes: .............................................................................................
Test plotting: ................
Pool: ...
Subset of incidence objects: ...........

DONE ===========================================================================
```


My session info is as follows

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin16.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] incidence_1.1.0 devtools_1.13.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12      digest_0.6.12     withr_2.0.0       grid_3.4.1        plyr_1.8.4       
 [6] gtable_0.2.0      scales_0.4.1.9002 ggplot2_2.2.1     rlang_0.1.2       lazyeval_0.2.0   
[11] tools_3.4.1       munsell_0.4.3     yaml_2.1.14       compiler_3.4.1    colorspace_1.3-2 
[16] memoise_1.1.0     tibble_1.3.3 
```

**Comment by caijun** [comment]
Wait a minute, I was not using the newest version of incidence. I will check it again.

**Comment by caijun** [comment]
I have checked with incidence 1.2.0 and the tests results are the same as above after deleting the rds files first.

**Comment by thibautjombart** [comment]
Hi there, 

deleting the `rds` files would always solve this kind of issues on the surface, as the files are re-generated and therefore then consistent with themselves after running subsequent checks. The problem with this is that you'd need to re-inspect every graphic manually to make sure they look as they should. The best course of action would be:
1. isolate the problematic plots
2. remove the corresponding `rds` (and only these)
3. re-generate the `rds` running `devtools::test()`
4. inspect the corresponding plots and make sure they're okay; if so, commit and push ;) 
Makes sense?

**Comment by caijun** [comment]
As with bullet 4, this means only the person who wrote the test case can know the correct plot. Moreover, in the long run, the author of the test case may also forget the purpose of the test case. To be honest, it was my first time to use `expect_equal_to_reference()` for testing when I firstly contributed to incidence. I don't think it's a good way to use `expect_equal_to_reference()` to compare results as it is very fuzzy and we don't know what we really want to test. We should write test case to be as specific as possible. 

For testing plots, my thoughts are 
1. Remove testing plots, we can make a range of plot examples generated by incidence. Everytime we update incidence, we will visually check whether those plot examples are correct. Actually, this already has been done by generating the vignettes.

Or

2. Keep testing plots, but we should write unit cases to test the elements of plots, such as x-axis tick labels, fitting lines.

**Comment by thibautjombart** [comment]
Not really, one can just check what the command line seems to create and verify that the plot makes sense. I don't remember every plot on the top of my head. 

It is by no means a perfect way to test plots, in fact it doesn't test rendering results, only object contents, and these are notoriously unreliable from one version of ggplot2 to the next. Unit testing graphics is a difficult issue, investigated by a few people at the moment as far as I know, but no definite solution so far. 

What do you mean by 'very fuzzy'? I thought it tested whether objects stored in the `rds` are `identical`?

As for your solution 1, it would add work compared to the existing. For now as far as the tests pass we can be reasonably sure the plots are unchanged, and we only need to check the ones that have changed. This seems quicker than re-checking every plot every time.

As for solution 2, this is what the current tests do, on the entirety of the `ggplot` objects.

**Comment by karawoo** [comment]
I don't know if you all are interested, but ggplot2 uses [vdiffr](https://github.com/lionel-/vdiffr) for visual tests and it's pretty handy. It diffs SVGs and provides a nice Shiny app that will let you toggle between the existing and failing versions of plots to compare them.

**Comment by caijun** [comment]
I think it is 'very fuzzy' as I think of the following case:

If ggplot2 updates by changing its default theme, such as the alignment of tick labels, these ggplot2 updates essentially have no impact on our incidence plots, but the objects stored in the `rds` would be different, which results in our tests failing. This is not what we would like to test.

Taking `(p.isoweek <- plot(i.isoweek))` and `(p.isoweek.2 <- plot(i.isoweek, labels_iso_week = FALSE))` as examples, I just care about whether the x-axis tick labels in isoweek format or not. The remaining plot elements can be ignored even if ggplot2 updates will change them.

**Comment by thibautjombart** [comment]
Just coming back to this. @caijun feel free to PR changes to the tests for plots; I think we still have an issue with `isoweeks` labels but will post an issue ASAP

**Comment by caijun** [comment]
I will explore using vdiffr to write plot tests for isoweeks labels.

**Comment by caijun** [comment]
I have rewritten all plot tests using *vdiffr*. see the PR https://github.com/reconhub/incidence/pull/27

@karawoo thanks for recommending *vdiffr*, which is quite useful for plot testing.

**Comment by thibautjombart** [comment]
@caijun sorry for taking forever to look into this; things will be crazy until the rest of the year then I'll become a human again. Also big thanks to @karawoo - this is exactly what we needed :) 

Thanks for the PR. In now. I'll need `incidence` for teaching at the Epidemics conf so will submit to CRAN after testing on `reconhub/devel` docker.
