### ISSUE TITLE
incidence::fit fails when there is only one non-zero incidence date

### ISSUE THREAD

**Issue by sangeetabhatia03** [reconhub/incidence#31]
The fit function fails is there is only one date for which we have non-zero incidence. While mathematically that makes sense, the error message does not make this obvious. 
```
x <- c(3, 0, 0, 0, 0, 0, 0, 0)
incid <- incidence::as.incidence(x, interval = 7)
incidence::fit(incid)
```
produces the following error
`Error in if (r[1] > 0) { : missing value where TRUE/FALSE needed`

The error is produced in the function extract_info (line 295 in fit.R). I think that this can be prevented by checking that there are at least 2 points in x after non-zero incidence have been filtered out.

**Comment by thibautjombart** [comment]
Thanks for flagging this. We should not fit a model if there is only one value, indeed. Simplest option is throw an error, probably preferable to returning `NULL` with a warning. 

Would you like to PR this?

**Comment by sangeetabhatia03** [comment]
Sure, will do.
