### ISSUE TITLE
Group hierarchies

### ISSUE THREAD

**Issue by zkamvar** [reconhub/incidence#76]
Currently, users can group by a single factor, but it's often useful to group by two factors (e.g. age group and case definition). 

This could be applied to the current structure by implementing the `$counts` as an array.

**Comment by dirkschumacher** [comment]
How would you do a facet plot (in the ggplot2 sense)? Is this currently possible?

**Comment by zkamvar** [comment]
it is currently possible by adding `facet_wrap(~groups)`

**Comment by zkamvar** [comment]
I'm going to close this issue as the conversation as moved on to #104
