### ISSUE TITLE
Request feature: I want more coffee

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/incidence#80]
It would be great if *incidence* could make my coffee... yesterday was tough.

Ideally I should be able to do:
```
library(incidence)
make_my_coffee(type = ...) # should return an espresso
```

**Comment by zkamvar** [comment]
What you suggest is impossible.  

Try the rcoffee package. :)

**Comment by haskewc** [comment]
I think thats a great idea :)

**Comment by dirkschumacher** [comment]
We can add it as an Easter egg for folks that actually read the docs :)
