### ISSUE TITLE
stegen not converting dates

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/incidence#88]
Stegen case study: not converting dates to dates does not generate errors, but does not work either - dispatching is not working, try and see why, make sure we issue a meaningful error. 

This comes from:
```
incidence("2001-01-01")
```
Not working.

**Comment by zkamvar** [comment]
This was a bit difficult for me to parse when I first read it. 

For future contributors: please use the [reprex package](http://cran.r-project.org/package=reprex) to make a reproducible example like so:

```r
reprex::reprex({
library("incidence")
res <- incidence("2001-01-01")
str(res)
})
```

This would copy the formatted code to your clipboard that you can paste directly into github:

``` r
library("incidence")
res <- incidence("2001-01-01")
str(res)
#>  Date[1:1], format: "2001-01-01"
```

<sup>Created on 2019-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This method makes it easier for us to figure out what the actual behavior was and if we can fix it.
